# Generated by Django 4.2.3 on 2023-07-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryoforigin',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='Product.countryoforigin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product', to='Product.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.ManyToManyField(related_name='product', to='Product.season'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='product', to='Product.size'),
        ),
    ]
